// <auto-generated />
namespace Fit4Life.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fit4LifeDBv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fit4LifeDBv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904041010597_Fit4LifeDBv1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
